name: publish comanda.contracts nuget package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore comanda.contracts/Source/Comanda.Contracts.csproj

    - name: Build project
      run: dotnet build comanda.contracts/Source/Comanda.Contracts.csproj --configuration Release --output ./nupkg

    - name: Create NuGet package
      run: dotnet pack comanda.contracts/Source/Comanda.Contracts.csproj --configuration Release --output ./nupkg

    - name: Publish package to NuGet.org
      uses: NuGet/setup-nuget@v1.1.1

    - name: Push package
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
